"""add description fields to card

Revision ID: 0540256682e0
Revises: 3bd2eb068ca3
Create Date: 2026-08-04 10:16:12.154605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0540256682e0'
down_revision: Union[str, Sequence[str], None] = '3bd2eb068ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('front_description', sa.String(), nullable=True))
    op.add_column('card', sa.Column('back_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'back_description')
    op.drop_column('card', 'front_description')
    # ### end Alembic commands ###
